# Generated by Django 6.0.2 on 2026-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artists/')),
            ],
        ),
    ]
