# Generated by Django 6.0.2 on 2026-03-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_options_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
