# Generated by Django 6.0.2 on 2026-03-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='embed_link',
            field=models.URLField(blank=True),
        ),
    ]
