# Generated by Django 5.2.7 on 2026-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='embed_link',
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
