# Generated by Django 6.0.2 on 2026-03-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_creator_song_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('title', 'artist')},
        ),
    ]
