# Generated by Django 6.0.2 on 2026-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_song_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='chords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
